services:
  firebase:
    build:
      context: .
      dockerfile: Dockerfile.Firebase
    ports:
      - "9099:9099"  # Auth emulator
      - "8080:8080"  # Firestore emulator
      - "4000:4000"  # Emulator UI  http://localhost:4000
      - "4400:4400"  # Emulator hub

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    depends_on:
      - firebase
